### ISSUE TITLE
Unable to view created PDF

### ISSUE THREAD

**Issue by NiroopNife** [rohitsangwan01/flutter_full_pdf_viewer_null_safe#1]
I was creating a PDF file with the help of the PDF dependency & creating a file. Passed that file to the PDFViewerScaffold but getting an error stating as
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel flutter_full_pdf_viewer)
E/flutter ( 7509): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): 
E/flutter ( 7509): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_full_pdf_viewer)
E/flutter ( 7509): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): #1      PDFViewerPlugin.launch (package:flutter_full_pdf_viewer_null_safe/full_pdf_viewer_plugin.dart:38:5)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): 
```

Minimum SDK is 21 & do have added the ndk filters too

**Comment by undamatlamanikanta** [comment]
face same issues

Unhandled Exception: MissingPluginException(No implementation found for method close on channel flutter_full_pdf_viewer)

**Comment by ghost** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel flutter_full_pdf_viewer)
E/flutter ( 7509): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): 
E/flutter ( 7509): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_full_pdf_viewer)
E/flutter ( 7509): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): #1      PDFViewerPlugin.launch (package:flutter_full_pdf_viewer_null_safe/full_pdf_viewer_plugin.dart:38:5)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509):

**Comment by RafaJMoraes** [comment]
Passo pelo mesmo problema.

 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel flutter_full_pdf_viewer)
E/flutter (27972): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (27972): <asynchronous suspension>
E/flutter (27972): 
E/flutter (27972): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_full_pdf_viewer)
E/flutter (27972): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (27972): <asynchronous suspension>
E/flutter (27972): #1      PDFViewerPlugin.launch (package:flutter_full_pdf_viewer_null_safe/full_pdf_viewer_plugin.dart:38:5)
E/flutter (27972): <asynchronous suspension>

**Comment by osmarsouza** [comment]
@RafaJMoraes você, ou alguém, conseguiu resolver esse problema?

@RafaJMoraes did you, or someone else, manage to solve this problem?
